{
 "face_hair": {
    "face_hair-n_newbasicfacehairupper17": "Chevron Mustache",
    "face_hair-n_newbasicfacehairupper16": "Cantinflas",
    "face_hair-n_newbasicfacehairupper15": "Walrus Mustache",
    "face_hair-n_newbasicfacehairupper14": "Toothbrush Mustache",
    "face_hair-n_newbasicfacehairupper13": "Dali Mustache",
    "face_hair-n_newbasicfacehairupper08": "The Mario",
    "face_hair-n_newbasicfacehairupper07": "Downward English",
    "face_hair-n_newbasicfacehairupper06": "Horseshoe",
    "face_hair-n_newbasicfacehairupper05": "Handlebar",
    "face_hair-n_newbasicfacehairupper04": "Dallas Mustache",
    "face_hair-n_newbasicfacehairupper02": "Long Stubble Mustache",
    "face_hair-n_newbasicfacehairupper01": "Stubble Mustache",
    "face_hair-n_newbasicfacehairlower20": "Small Sideburn",
    "face_hair-n_newbasicfacehairlower18": "Mutton Chops",
    "face_hair-n_newbasicfacehairlower17": "Long Sideburn",
    "face_hair-n_newbasicfacehairlower16": "Full Beard",
    "face_hair-n_newbasicfacehairlower13": "Garibaldi Beard",
    "face_hair-n_newbasicfacehairlower12": "Shaggy Beard",
    "face_hair-n_newbasicfacehairlower09": "Long Goatee",
    "face_hair-n_newbasicfacehairlower08b": "Corporate Beard",
    "face_hair-n_newbasicfacehairlower07": "Brett Beard",
    "face_hair-n_newbasicfacehairlower06": "Pointy Chin Beard",
    "face_hair-n_newbasicfacehairlower05": "Soul Patch",
    "face_hair-n_newbasicfacehairlower04": "Extended Soul Patch",
    "face_hair-n_newbasicfacehairlower02new": "Long Stubble",
    "face_hair-n_newbasicfacehairlower02bnew": "Stubble Goatee",
    "face_hair-n_newbasicfacehairlower01": "Light Stubble"
},
  "eyebrow": {
    "eyebrow-n_basic2018newbrows17": "Wave Brow",
    "eyebrow-n_basic2018newbrows16": "Tapered Brow",
    "eyebrow-n_basic2018newbrows15": "Straight Brows",
    "eyebrow-n_basic2018newbrows14": "Shaved Brow",
    "eyebrow-n_basic2018newbrows13": "Eyebrow Piercing",
    "eyebrow-n_basic2018newbrows12": "Upset Brows",
    "eyebrow-n_basic2018newbrows11": "Angry Brows",
    "eyebrow-n_basic2018newbrows10": "Short Brows",
    "eyebrow-n_basic2018newbrows09": "Sculpted Brows",
    "eyebrow-n_basic2018newbrows08": "Wiggle Brows",
    "eyebrow-n_basic2018newbrows07": "Fuzzy Brows",
    "eyebrow-n_basic2018newbrows06": "Peaked Brows",
    "eyebrow-n_basic2018newbrows05": "Isosceles Brows",
    "eyebrow-n_basic2018newbrows04": "Felt Brows",
    "eyebrow-n_basic2018newbrows03": "Bracket Brows",
    "eyebrow-n_basic2018newbrows02": "Boxy Brows",
    "eyebrow-n_basic2018newbrows01": "Angular Brows",
    "eyebrow-n_29": "Downturned brows",
    "eyebrow-n_27": "Crazy brows",
    "eyebrow-n_26": "Dainty brows",
    "eyebrow-n_25": "Alien brows",
    "eyebrow-n_23": "Model brows",
    "eyebrow-n_22": "Demanding brows",
    "eyebrow-n_21": "Thin brows",
    "eyebrow-n_19": "Demour brows",
    "eyebrow-n_18": "Crisp brows",
    "eyebrow-n_11": "Dash Brows",
    "eyebrow-n_10": "Perfect brows",
    "eyebrow-n_08": "Frown brows",
    "eyebrow-n_07": "Penciled brows",
    "eyebrow-n_06": "Badboy brows",
    "eyebrow-n_04": "Sharp brows",
    "eyebrow-n_03": "Thick brows",
    "eyebrow-n_02": "Crescent brows",
    "eyebrow-n_01": "Grandpa brows"
},
  "eye": {
    "eye-n_basic2018zanyeyes": "Zany Eyes",
    "eye-n_basic2018woaheyes": "Woah Eyes",
    "eye-n_basic2018wingedliner": "Winged Eyeliner",
    "eye-n_basic2018teardrop": "Tear Drop Eyes",
    "eye-n_basic2018starryeye": "Starry Eye",
    "eye-n_basic2018squintynude": "Squinty Nude Eye",
    "eye-n_basic2018snakeeyes": "Snake Eyes",
    "eye-n_basic2018smokeyeye2": "Dark Shadow",
    "eye-n_basic2018slantednude": "Slanted Nude Eye",
    "eye-n_basic2018redeyes": "Red Eyes",
    "eye-n_basic2018pinkshadow2": "Light Shadow",
    "eye-n_basic2018nudesquare": "Square Nude Eye",
    "eye-n_basic2018nudediamond": "Diamond Nude Eye",
    "eye-n_basic2018malesquareupturned": "Upturned Square (masc)",
    "eye-n_basic2018malesquaresquint": "Squinty Square (masc)",
    "eye-n_basic2018malesquaresleepy": "Sleepy Square (masc)",
    "eye-n_basic2018malesquaredroopy": "Droopy Square (masc)",
    "eye-n_basic2018malesquare": "Square (masculine)",
    "eye-n_basic2018maleroundupturned": "Upturned Round (masc)",
    "eye-n_basic2018maleroundsquint": "Squinty Round (masc)",
    "eye-n_basic2018maleroundsleepy": "Sleepy Round (masc)",
    "eye-n_basic2018malerounddroopy": "Droopy Round (masc)",
    "eye-n_basic2018maleround": "Round (masculine)",
    "eye-n_basic2018malediamondupturned": "Upturned Diamond (masc)",
    "eye-n_basic2018malediamondsquint": "Squinty Diamond (masc)",
    "eye-n_basic2018malediamondsleepy": "Sleepy Diamond (masc)",
    "eye-n_basic2018malediamonddroopy": "Droopy Diamond (masc)",
    "eye-n_basic2018malediamond": "Diamond (masculine)",
    "eye-n_basic2018malealmondupturned": "Upturned Almond (masc)",
    "eye-n_basic2018malealmondsquint": "Squinty Almond (masc)",
    "eye-n_basic2018malealmond": "Almond (masculine)",
    "eye-n_basic2018liftedeyes": "Lifted Eyes",
    "eye-n_basic2018holloweyes": "Empty Eyes",
    "eye-n_basic2018heavymascera": "Heavy Mascara",
    "eye-n_basic2018guyliner": "Guy Liner",
    "eye-n_basic2018goldshadow2": "Earthy Shadow",
    "eye-n_basic2018femalesquareupturned": "Upturned Square (fem)",
    "eye-n_basic2018femalesquaresquint": "Squinty Square (fem)",
    "eye-n_basic2018femalesquaresleepy": "Sleepy Square (fem)",
    "eye-n_basic2018femalesquaredroopy": "Droopy Square (fem)",
    "eye-n_basic2018femalesquare": "Square (Feminine)",
    "eye-n_basic2018femalesovalsquint": "Squinty Oval (fem)",
    "eye-n_basic2018femaleroundupturned": "Upturned Round (fem)",
    "eye-n_basic2018femaleroundsleepy": "Sleepy Round (fem)",
    "eye-n_basic2018femalerounddroopy": "Droopy Round (fem)",
    "eye-n_basic2018femaleround": "Round (feminine)",
    "eye-n_basic2018femaleovalslant": "Slanted Oval (fem)",
    "eye-n_basic2018femaleovaldroopy": "Droopy Oval (fem)",
    "eye-n_basic2018femalediamondupturned": "Upturned Diamond (fem)",
    "eye-n_basic2018femalediamondsquint": "Squinty Diamond (fem)",
    "eye-n_basic2018femalediamondsleepy": "Sleepy Diamond (fem)",
    "eye-n_basic2018femalediamond": "Diamond (Feminine)",
    "eye-n_basic2018femalealmoundsquint": "Squinty Almond (fem)",
    "eye-n_basic2018femalealmond": "Almond (Feminine)",
    "eye-n_basic2018falselashes": "False Eyelashes",
    "eye-n_basic2018downturnedoval": "Downturned Oval",
    "eye-n_basic2018doublewing": "Double Wing Eyeliner",
    "eye-n_basic2018dolleyes": "Doll Eyes",
    "eye-n_basic2018doeeyes": "Doe Eyes",
    "eye-n_basic2018definedlashes": "Defined Lashes",
    "eye-n_basic2018crescent": "Squinty Crescent",
    "eye-n_basic2018butterflyeyes": "Butterfly Eyes",
    "eye-n_basic2018blockeyes": "Blocky Eyes",
    "eye-n_basic2018animeeyes": "Basic Anime Eyes",
    "eye-n_basic2018angryeyes": "Angry Eyes"
 },
  "nose": {
    "nose-n_room22019nosestud": "Nose Stud",
    "nose-n_basic2018newnose20": "Dot Nose",
    "nose-n_basic2018newnose19": "Freckle Nose",
    "nose-n_basic2018newnose18": "Silver Nose Ring",
    "nose-n_basic2018newnose17": "Septum Piercing",
    "nose-n_basic2018newnose16": "Angular Nose",
    "nose-n_basic2018newnose15": "Button Nose",
    "nose-n_basic2018newnose14": "Soft Nose",
    "nose-n_basic2018newnose13": "Hooked Nose",
    "nose-n_basic2018newnose11": "Bean Nose",
    "nose-n_basic2018newnose09": "Bulb Nose",
    "nose-n_basic2018newnose05": "Straight Nose",
    "nose-n_basic2018newnose04": "Pinched Nose",
    "nose-n_basic2018newnose03": "Teardrop Nose",
    "nose-n_26": "Bubble Nose",
    "nose-n_23": "Defined Nose",
    "nose-n_19": "Sledge Nose",
    "nose-n_12_b": "Sharper Nose",
    "nose-n_12": "Sharp Nose",
    "nose-n_07_b": "Thicker Nose",
    "nose-n_07": "Flared Nose",
    "nose-n_03_b": "Ramp Nose",
    "nose-n_03": "Slope Nose",
    "nose-n_01_b": "Dainty Nose",
    "nose-n_01": "Baby Nose"
},

  "mouth": {
    "mouth-n_room22019sillymouth": "Silly Mouth",
    "mouth-n_basic2018widethinround": "Wide Thin Round Lips",
    "mouth-n_basic2018widethinpeaked": "Wide Thin Peaked Lips",
    "mouth-n_basic2018widefullround": "Wide Full Round Lips",
    "mouth-n_basic2018widefullpeaked": "Wide Full Peaked Lips",
    "mouth-n_basic2018toothythinround": "Toothy Thin Round Lips",
    "mouth-n_basic2018toothythinpeaked": "Toothy Thin Peaked Lips",
    "mouth-n_basic2018toothyfullround": "Toothy Full Round Lips",
    "mouth-n_basic2018toothyfullpeaked": "Toothy Full Peaked Lips",
    "mouth-n_basic2018puckerthinround": "Puckered Thin Round Lips",
    "mouth-n_basic2018puckerthinpeaked": "Puckered Thin Peaked Lips",
    "mouth-n_basic2018puckerfullround": "Puckered Full Round Lips",
    "mouth-n_basic2018puckerfullpeaked": "Puckered Full Peaked Lips",
    "mouth-n_basic2018pillowthinround": "Pillowy Thin Round Lips",
    "mouth-n_basic2018pillowthinpeaked": "Pillowy Thin Peaked Lips",
    "mouth-n_basic2018pillowfullround": "Pillowy Full Round Lips",
    "mouth-n_basic2018pillowfullpeaked": "Pillowy Full Peaked Lips",
    "mouth-n_basic2018agapethinground": "Parted Thin Round Lips",
    "mouth-n_basic2018agapethingpeaked": "Parted Thin Peaked Lips",
    "mouth-n_basic2018agapefullround": "Parted Full Round Lips",
    "mouth-n_basic2018agapefullpeaked": "Parted Full Peaked Lips",
    "mouth-basic2018yummouth": "Yum! Mouth",
    "mouth-basic2018whistlemouth": "Whistle Mouth",
    "mouth-basic2018vampteeth": "Vamp Teeth",
    "mouth-basic2018upsetmouth": "Upset Mouth",
    "mouth-basic2018unimpressed": "Unimpressed Mouth",
    "mouth-basic2018tongueout": "Tongue Out Mouth",
    "mouth-basic2018thinround": "Basic Round Thin Lips",
    "mouth-basic2018thinpeaked": "Basic Peaked Thin Lips",
    "mouth-basic2018smugmouth": "Smug Mouth",
    "mouth-basic2018smirk": "Smirk Mouth",
    "mouth-basic2018poutthinround": "Pout Round Thin Lips",
    "mouth-basic2018poutthinpeaked": "Pout Peaked Thin Lips",
    "mouth-basic2018poutfullround": "Pout Round Full Lips",
    "mouth-basic2018poutfullpeaked": "Pout Peaked Full Lips",
    "mouth-basic2018openthinround": "Open Round Thin Lips",
    "mouth-basic2018openthinpeaked": "Open Peaked Thin Lips",
    "mouth-basic2018openfullround": "Open Round Full Lips",
    "mouth-basic2018openfullpeaked": "Open Peaked Full Lips",
    "mouth-basic2018lollipop": "Lollipop Mouth",
    "mouth-basic2018lippiercing": "Lip Piercing",
    "mouth-basic2018grin": "Grin",
    "mouth-basic2018fullround": "Basic Round Full Lips",
    "mouth-basic2018fullpeaked": "Basic Peaked Full Lips",
    "mouth-basic2018downturnedthinround": "Downturn Round Thin Lips",
    "mouth-basic2018downturnedthinpeaked": "Downturn Peaked Thin Lips",
    "mouth-basic2018downturnedfullround": "Downturn Round Full Lips",
    "mouth-basic2018downturnedfullpeaked": "Downturn Peaked Full Lips",
    "mouth-basic2018chubbymouth": "Chubby Mouth",
    "mouth-basic2018chippermouth": "Chipper Mouth",
    "mouth-basic2018charmer": "Charmer Mouth",
    "mouth-basic2018bunnyteeth": "Buck Teeth"  
},
  "hair_front": {
    "hair_front-n_malenew33": "Short Short Fro",
    "hair_front-n_malenew32": "Box Braids",
    "hair_front-n_malenew31": "Long Undercut Dreads",
    "hair_front-n_malenew30": "Undercut Dreads",
    "hair_front-n_malenew29": "Side Swept Fro",
    "hair_front-n_malenew27": "Long Buzzed Fro",
    "hair_front-n_malenew26": "Short Buzzed Fro",
    "hair_front-n_malenew25": "Curly Undercut",
    "hair_front-n_malenew24": "Tight curls",
    "hair_front-n_malenew23": "Loose Curls",
    "hair_front-n_malenew22": "Shaggy Curls",
    "hair_front-n_malenew21": "Short Curls",
    "hair_front-n_malenew20": "Medium Wavy Cut",
    "hair_front-n_malenew19": "Short Wavy Cut",
    "hair_front-n_malenew18": "Wavy Undercut",
    "hair_front-n_malenew17": "Wavy Side Part",
    "hair_front-n_malenew16": "Shaggy Side Part",
    "hair_front-n_malenew15": "Combed Back Waves",
    "hair_front-n_malenew14": "Blown Back Waves",
    "hair_front-n_malenew13": "Short Straight",
    "hair_front-n_malenew12": "Side Combed Straight",
    "hair_front-n_malenew11": "Straight Slicked Back",
    "hair_front-n_malenew10": "Buzz Cut",
    "hair_front-n_malenew09": "Shaggy Crew Cut",
    "hair_front-n_malenew08": "Faux Hawk",
    "hair_front-n_malenew07": "Shaggy Straight",
    "hair_front-n_malenew06": "Straight Side Part",
    "hair_front-n_malenew05": "Combed Back Undercut",
    "hair_front-n_malenew04": "Upward Swoosh",
    "hair_front-n_malenew03": "Side Swept Undercut",
    "hair_front-n_malenew02": "Side Swept",
    "hair_front-n_malenew01": "Crew Cut",
    "hair_front-n_basic2020overshoulderwavyshort": "Over Shoulder Wavy Short",
    "hair_front-n_basic2020overshoulderwavy": "Over Shoulder Wavy Long",
    "hair_front-n_basic2020overshoulderstraightshort": "Over Shoulder Straight Short",
    "hair_front-n_basic2020overshoulderstraightbangs": "Over Shoulder Straight Bangs",
    "hair_front-n_basic2020overshoulderstraight": "Over Shoulder Straight Long",
    "hair_front-n_basic2020overshoulderpony": "Over Shoulder Pony",
    "hair_front-n_basic2020overshouldercurly": "Over Shoulder Curly",
    "hair_front-n_basic2020overshouldercoily": "Over Shoulder Coily",
    "hair_front-n_basic2020overshoulderbraid": "Over Shoulder Braid",
    "hair_front-n_basic2019wavyoffsetpart": "Wavy Offset Part",
    "hair_front-n_basic2019wavyflipdroop": "Wavy Flipped Droopy Bang",
    "hair_front-n_basic2019wavyflipbangs": "Wavy Flipped Bangs",
    "hair_front-n_basic2019wavychunkysidebang": "Chunky Wave Side Bang",
    "hair_front-n_basic2019faceframewaves": "Face Frame Waves",
    "hair_front-n_basic2019bluntbangswithwaves": "Blunt Bangs With Loose Waves",
    "hair_front-n_basic2018wavysidebangs": "Wavy Side Bangs",
    "hair_front-n_basic2018wavypulledback": "Wavy Pulled Back",
    "hair_front-n_basic2018wavynobangs": "Wavy No Bangs",
    "hair_front-n_basic2018wavylowpart": "Wavy Low Pulled Back",
    "hair_front-n_basic2018wavyhalfup": "Wavy Half Pulled Back",
    "hair_front-n_basic2018wavyfullbangs": "Wavy Full Bangs",
    "hair_front-n_basic2018wavybettiebangs": "Bettie Bangs",
    "hair_front-n_basic2018wavybabybangs": "Wavy Baby Bangs",
    "hair_front-n_basic2018topknotwithbangs": "Top Knot with Bangs",
    "hair_front-n_basic2018topknot": "Top Knot",
    "hair_front-n_basic2018straightwhispybangs": "Straight Wispy Bangs",
    "hair_front-n_basic2018straightsidebangs": "Straight Side Bangs",
    "hair_front-n_basic2018straightpulledback": "Straight Pulled Back",
    "hair_front-n_basic2018straightnobangs": "Straight No Bangs",
    "hair_front-n_basic2018straightlowsidepart": "Straight Low Pulled Back",
    "hair_front-n_basic2018straightfullbangs": "Straight Full Bangs",
    "hair_front-n_basic2018straightbluntbangs": "Blunt Bangs",
    "hair_front-n_basic2018straightbangslowpart": "Straight Low Pulled Back With Bangs",
    "hair_front-n_basic2018straightbabybangs": "Straight Baby Bangs",
    "hair_front-n_basic2018sleekstraightpart": "Sleek Straight Part",
    "hair_front-n_basic2018sidebangspulledback": "Side Bangs Pulled Back",
    "hair_front-n_basic2018pulledbackbangs": "Pulled Back with Bangs",
    "hair_front-n_basic2018pulledback": "Simple Pulled Back",
    "hair_front-n_basic2018pigtailpart": "Pig Tail Part",
    "hair_front-n_basic2018mediumwavybettiebangs": "Bettie Bangs",
    "hair_front-n_basic2018mediumcurlymarilyn": "Marilyn Curls",
    "hair_front-n_basic2018marilyncurls": "Marilyn Curls",
    "hair_front-n_basic2018longwavytopknot": "Wavy Pulled Back Bangs",
    "hair_front-n_basic2018longstraighthalfpony": "Chunky Side Swept Bangs",
    "hair_front-n_basic2018dreadssidebangs": "Dreads Side Bangs",
    "hair_front-n_basic2018dreadspulledback": "Dreads Pulled Back",
    "hair_front-n_basic2018dreadsnobangs": "Dreads No Bangs",
    "hair_front-n_basic2018dreadsfullbangs": "Dreads Full Bangs",
    "hair_front-n_basic2018doubletopknots": "Double Top Knots",
    "hair_front-n_basic2018curlysidebangs": "Curly Side Bangs",
    "hair_front-n_basic2018curlypulledback": "Curly Pulled Back",
    "hair_front-n_basic2018curlynobangs": "Curly No Bangs",
    "hair_front-n_basic2018curlyfullbangs": "Curly Full Bangs",
    "hair_front-n_basic2018coilysidepart": "Coily Side Part",
    "hair_front-n_basic2018coilypinapple": "Coily Pinapple Hair",
    "hair_front-n_basic2018coilyhalfbun": "Coily Half Bun",
    "hair_front-n_basic2018coilssidebangs": "Coils Side Part",
    "hair_front-n_basic2018coilsfront": "Coils Front",
    "hair_front-n_basic2018buzzcut": "Bald",
    "hair_front-n_basic2018afropompoms": "Afro Pom Poms",
    "hair_front-n_basic2018afrofront": "Afro Front"
}
  },
 "hair_back": {
    "hair_back-n_malenew33": "Short Short Fro",
    "hair_back-n_malenew32": "Box Braids",
    "hair_back-n_malenew31": "Long Undercut Dreads",
    "hair_back-n_malenew30": "Undercut Dreads",
    "hair_back-n_malenew29": "Side Swept Fro",
    "hair_back-n_malenew27": "Long Buzzed Fro",
    "hair_back-n_malenew26": "Short Buzzed Fro",
    "hair_back-n_malenew25": "Curly Undercut",
    "hair_back-n_malenew24": "Tight Curls",
    "hair_back-n_malenew23": "Loose Curls",
    "hair_back-n_malenew22": "Shaggy Curls",
    "hair_back-n_malenew21": "Short Curls",
    "hair_back-n_malenew20": "Medium Wavy Cut",
    "hair_back-n_malenew19": "Short Wavy Cut",
    "hair_back-n_malenew18": "Wavy Undercut",
    "hair_back-n_malenew17": "Wavy Side Part",
    "hair_back-n_malenew16": "Shaggy Side Part",
    "hair_back-n_malenew15": "Combed Back Waves",
    "hair_back-n_malenew14": "Blown Back Waves",
    "hair_back-n_malenew13": "Short Straight",
    "hair_back-n_malenew12": "Side Combed Straight",
    "hair_back-n_malenew11": "Straight Slicked Back",
    "hair_back-n_malenew10": "Buzz Cut",
    "hair_back-n_malenew09": "Shaggy Crew Cut",
    "hair_back-n_malenew08": "Faux Hawk",
    "hair_back-n_malenew07": "Shaggy Straight",
    "hair_back-n_malenew06": "Straight Side Part",
    "hair_back-n_malenew05": "Combed Back Undercut",
    "hair_back-n_malenew04": "Upward Swoosh",
    "hair_back-n_malenew03": "Side Swept Undercut",
    "hair_back-n_malenew02": "Side Swept",
    "hair_back-n_malenew01": "Crew Cut",
    "hair_back-n_basic2020overshoulderwavyshort": "Over Shoulder Wavy Short",
    "hair_back-n_basic2020overshoulderwavy": "Over Shoulder Wavy Long",
    "hair_back-n_basic2020overshoulderstraightshort": "Over Shoulder Straight Short",
    "hair_back-n_basic2020overshoulderstraightbangs": "Over Shoulder Straight Bangs",
    "hair_back-n_basic2020overshoulderstraight": "Over Shoulder Straight Long",
    "hair_back-n_basic2020overshoulderpony": "Over Shoulder Pony",
    "hair_back-n_basic2020overshouldercurly": "Over Shoulder Curly",
    "hair_back-n_basic2020overshouldercoily": "Over Shoulder Coily",
    "hair_back-n_basic2020overshoulderbraid": "Over Shoulder Braid",
    "hair_back-n_basic2019wavylongbob": "Wavy Long Bob",
    "hair_back-n_basic2019sweetcurls": "Sweet Curl Waves",
    "hair_back-n_basic2019poofbob": "Poofy Bob",
    "hair_back-n_basic2019medbeachwave": "Short Beach Waves",
    "hair_back-n_basic2019longbeachwave": "Long Beach Waves",
    "hair_back-n_basic2019glamourwaves": "Long Glamour Waves",
    "hair_back-n_basic2019bigchunkywaves": "Chunky Waves",
    "hair_back-n_basic2018wavyshort": "Wavy Short",
    "hair_back-n_basic2018wavymed": "Wavy Medium",
    "hair_back-n_basic2018wavylowpony": "Wavy Low Pony",
    "hair_back-n_basic2018wavyhighpony": "Wavy High Pony",
    "hair_back-n_basic2018wavyextrashort": "Wavy Pixie",
    "hair_back-n_basic2018wavyextralong": "Wavy Long",
    "hair_back-n_basic2018topknotback": "Top Knot Back",
    "hair_back-n_basic2018straightshortlowpigtails": "Straight Short Low Pigtails",
    "hair_back-n_basic2018straightshorthighpigtails": "Straight Short High Pigtails",
    "hair_back-n_basic2018straightshort": "Straight Short",
    "hair_back-n_basic2018straightmedium": "Straight Medium",
    "hair_back-n_basic2018straightlowpony": "Straight Low Pony",
    "hair_back-n_basic2018straightlonglowpigtails": "Straight Long Low Pigtails",
    "hair_back-n_basic2018straightlong": "Straight Long",
    "hair_back-n_basic2018straighthighpony": "Straight High Pony",
    "hair_back-n_basic2018straightextrashort": "Straight Pixie",
    "hair_back-n_basic2018sleekstraightpony": "Sleek Straight Pony",
    "hair_back-n_basic2018sleekstraightmedium": "Sleek Straight Medium",
    "hair_back-n_basic2018sleekstraightlong": "Sleek Straight Long",
    "hair_back-n_basic2018sleekstraightextrashort": "Sleek Straight Short",
    "hair_back-n_basic2018mediumwavybettiebangs": "Bettie Waves",
    "hair_back-n_basic2018mediumcurlymarilyn": "Marilyn Curls",
    "hair_back-n_basic2018loosecoilyshort": "Loose Coily Short",
    "hair_back-n_basic2018loosecoilymedium": "Loose Coily Medium",
    "hair_back-n_basic2018loosecoilylong": "Loose Coily Long",
    "hair_back-n_basic2018longwavytopknot": "Long Wavy Half Bun",
    "hair_back-n_basic2018longstraighthalfpony": "Half Pony",
    "hair_back-n_basic2018dreadsmedium": "Dreads Medium",
    "hair_back-n_basic2018dreadslowpony": "Dreads Low Pony",
    "hair_back-n_basic2018dreadslong": "Dreads Long",
    "hair_back-n_basic2018dreadshighpony": "Dreads High Pony",
    "hair_back-n_basic2018dreadsextrashort": "Dreads Extra Short",
    "hair_back-n_basic2018dreaddsshort": "Dreads Short",
    "hair_back-n_basic2018doubletopknotsback": "Double Top Knots Back",
    "hair_back-n_basic2018doublebunslow": "Low Double Buns",
    "hair_back-n_basic2018curlyshortlowpigtails": "Curly Short Low Pigtails",
    "hair_back-n_basic2018curlyshorthighpigtails": "Curly Short High Pigtails",
    "hair_back-n_basic2018curlyshort": "Curly No Bangs Back",
    "hair_back-n_basic2018curlymedium": "Curly Medium",
    "hair_back-n_basic2018curlylowpony": "Curly Low Pony",
    "hair_back-n_basic2018curlylonghighpigtails": "Curly Long High Pigtails",
    "hair_back-n_basic2018curlylong": "Curly Long",
    "hair_back-n_basic2018curlyhighpony": "Curly High Pony",
    "hair_back-n_basic2018curlyextrashort": "Curly Pixie",
    "hair_back-n_basic2018coilyshort": "Coily Short",
    "hair_back-n_basic2018coilypinappleback": "Coily Pinapple Hair",
    "hair_back-n_basic2018coilymedium": "Coily Medium",
    "hair_back-n_basic2018coilylowpony": "Coily Low Pony",
    "hair_back-n_basic2018coilylong": "Coily Long",
    "hair_back-n_basic2018coilyhighpony": "Coily High Pony",
    "hair_back-n_basic2018buzzcut": "Bald",
    "hair_back-n_basic2018bunlow": "Low Bun",
    "hair_back-n_basic2018bunhigh": "High Bun",
    "hair_back-n_basic2018afroshort": "Afro Short",
    "hair_back-n_basic2018afropompomsback": "Afro Pom Poms Back",
    "hair_back-n_basic2018afromedium": "Afro Medium",
    "hair_back-n_basic2018afrolong": "Afro Long",
    "hair_back-n_basic2018afrohighpony": "Afro High Pony"
},
  "shirt": {
    "shirt-n_starteritems2019tankwhite": "Tank - White",
    "shirt-n_starteritems2019tankblack": "Tank - Black",
    "shirt-n_starteritems2019raglanwhite": "Raglan - White",
    "shirt-n_starteritems2019raglanblack": "Raglan - Black",
    "shirt-n_starteritems2019pulloverwhite": "Pullover - White",
    "shirt-n_starteritems2019pulloverblack": "Pullover - Black",
    "shirt-n_starteritems2019maletshirtwhite": "Basic T-shirt - White",
    "shirt-n_starteritems2019maletshirtblack": "Basic T-shirt - Black",
    "shirt-n_starteritems2019femtshirtwhite": "Basic T-shirt - White",
    "shirt-n_starteritems2019femtshirtblack": "Basic T-shirt - Black",
    "shirt-n_room32019slouchyredtrackjacket": "Red Off-shoulder Track Jacket",
    "shirt-n_room32019malepuffyjacketgreen": "Green Puffer and T",
    "shirt-n_room32019longlineteesweatshirtgrey": "Grey Sweatshirt & Tee",
    "shirt-n_room32019jerseywhite": "White Vintage Jersey",
    "shirt-n_room32019hoodiered": "Red Raglan Hoodie",
    "shirt-n_room32019femalepuffyjacketgreen": "Green Puffer and Bra Top",
    "shirt-n_room32019denimjackethoodie": "Yellow Hoodie Denim Jacket",
    "shirt-n_room32019croppedspaghettitankblack": "Black Spaghetti Tank",
    "shirt-n_room22109plaidjacket": "Plaid Jacket",
    "shirt-n_room22109denimjacket": "Classic Denim Jacket",
    "shirt-n_room22019tuckedtstripes": "Striped Shirt",
    "shirt-n_room22019overalltop": "Denim Overall Top",
    "shirt-n_room22019denimdress": "Denim Overall Dress",
    "shirt-n_room22019bratoppink": "Pink Bra Top",
    "shirt-n_room12019sweaterwithbuttondowngrey": "Plain Layered Grey Sweater",
    "shirt-n_room12019cropsweaterwhite": "White Cropped Sweater",
    "shirt-n_room12019cropsweaterblack": "Black Cropped Sweater",
    "shirt-n_room12019buttondownblack": "Black Button Down",
    "shirt-n_philippineday2019filipinotop": "Elegant Top",
    "shirt-n_flashysuit": "Flashy Suit",
    "shirt-n_SCSpring2018flowershirt": "Daisy Crop-Top",
    "shirt-n_2016fallblacklayeredbomber": "Sport Bomber",
    "shirt-n_2016fallblackkknottedtee": "Black Knotted Tee",
    "shirt-f_skullsweaterblack": "Black Skull Sweater",
    "shirt-f_punklace": "Punk Lace",
    "shirt-f_plaidtiedshirtred": "Red Tied Plaid Shirt",
    "shirt-f_marchingband": "Marching Band Top"
  
},
  "pants": {
    "shorts-f_pantyhoseshortsnavy": "Navy Shorts w/ Pantyhose",
    "pants-n_starteritems2019mensshortswhite": "Basic Shorts - White",
    "pants-n_starteritems2019mensshortsblue": "Basic Shorts - Blue",
    "pants-n_starteritems2019mensshortsblack": "Basic Shorts - Black",
    "pants-n_starteritems2019cuffedshortswhite": "Cuffed Shorts - White",
    "pants-n_starteritems2019cuffedshortsblue": "Cuffed Shorts - Blue",
    "pants-n_starteritems2019cuffedshortsblack": "Cuffed Shorts - Black",
    "pants-n_starteritems2019cuffedjeanswhite": "Cuffed Jeans - White",
    "pants-n_starteritems2019cuffedjeansblue": "Cuffed Jeans - Blue",
    "pants-n_starteritems2019cuffedjeansblack": "Cuffed Jeans - Black",
    "pants-n_room32019rippedpantswhite": "Ripped White Jeans",
    "pants-n_room32019rippedpantsblue": "Ripped Blue Jeans",
    "pants-n_room32019longtrackshortscamo": "Camo Track Shorts",
    "pants-n_room32019longshortswithsocksgrey": "Grey Long Shorts",
    "pants-n_room32019longshortswithsocksblack": "Black Long Shorts",
    "pants-n_room32019highwasittrackshortsblack": "Short Black Track Shorts",
    "pants-n_room32019baggytrackpantsred": "Red Baggy Trackpants",
    "pants-n_room32019baggytrackpantsgreycamo": "Grey Camo Baggy Trackpants",
    "pants-n_room22019undiespink": "Pink Undies",
    "pants-n_room22019undiesblack": "Black Undies",
    "pants-n_room22019techpantscamo": "Camo Tech Pants",
    "pants-n_room22019shortcutoffsdenim": "Short Denim Cut-Offs",
    "pants-n_room22019longcutoffsdenim": "Denim Cut-Offs",
    "pants-n_room12019rippedpantsblue": "Ripped Blue Denim",
    "pants-n_room12019rippedpantsblack": "Ripped Black Denim",
    "pants-n_room12019formalslackskhaki": "Khaki Formal Slacks",
    "pants-n_room12019formalslacksblack": "Plain Black Formal Slacks",
    "pants-n_room12019blackacidwashjeans": "Plain Black Acid Wash Jeans",
    "pants-n_2016fallgreyacidwashjeans": "Grey Acid Wash"
},
  "skirt": {
    "skirt-n_starteritems2018whiteskirt": "Basic Skirt - White",
    "skirt-n_starteritems2018blueskirt": "Basic Skirt - Blue",
    "skirt-n_starteritems2018blackskirt": "Basic Skirt - Black",
    "skirt-n_room22019skirtwithsocksplaid": "Plaid Skirt With Socks",
    "skirt-n_room22019skirtwithsocksblack": "Black Skirt With Socks",
    "skirt-n_room12019pleatedskirtpink": "Pleated Pink Skirt",
    "skirt-n_room12019pleatedskirtgrey": "Pleated Skirt Grey",
    "skirt-n_room12019pleatedskirtblack": "Pleated Black Skirt",
    "skirt-f_gianttutu": "Tutu"
}
}
