{
  "face_hair": {
    "face_hair-n_newbasicfacehairupper17": "Chevron Mustache",
    "face_hair-n_newbasicfacehairupper16": "Cantinflas",
    "face_hair-n_newbasicfacehairupper15": "Walrus Mustache",
    ...
  },
  "hair_front": {
    "hair_front-n_malenew33": "Short Short Fro",
    "hair_front-n_malenew32": "Box Braids",
    "hair_front-n_malenew31": "Long Undercut Dreads",
    "hair_front-n_malenew30": "Undercut Dreads",
    "hair_front-n_malenew29": "Side Swept Fro",
    "hair_front-n_malenew27": "Long Buzzed Fro",
    "hair_front-n_malenew26": "Short Buzzed Fro",
    "hair_front-n_malenew25": "Curly Undercut",
    "hair_front-n_malenew24": "Tight curls",
    "hair_front-n_malenew23": "Loose Curls",
    "hair_front-n_malenew22": "Shaggy Curls",
    "hair_front-n_malenew21": "Short Curls",
    "hair_front-n_malenew20": "Medium Wavy Cut",
    "hair_front-n_malenew19": "Short Wavy Cut",
    "hair_front-n_malenew18": "Wavy Undercut",
    "hair_front-n_malenew17": "Wavy Side Part",
    "hair_front-n_malenew16": "Shaggy Side Part",
    "hair_front-n_malenew15": "Combed Back Waves",
    "hair_front-n_malenew14": "Blown Back Waves",
    "hair_front-n_malenew13": "Short Straight",
    "hair_front-n_malenew12": "Side Combed Straight",
    "hair_front-n_malenew11": "Straight Slicked Back",
    "hair_front-n_malenew10": "Buzz Cut",
    "hair_front-n_malenew09": "Shaggy Crew Cut",
    "hair_front-n_malenew08": "Faux Hawk",
    "hair_front-n_malenew07": "Shaggy Straight",
    "hair_front-n_malenew06": "Straight Side Part",
    "hair_front-n_malenew05": "Combed Back Undercut",
    "hair_front-n_malenew04": "Upward Swoosh",
    "hair_front-n_malenew03": "Side Swept Undercut",
    "hair_front-n_malenew02": "Side Swept",
    "hair_front-n_malenew01": "Crew Cut",
    "hair_front-n_basic2020overshoulderwavyshort": "Over Shoulder Wavy Short",
    "hair_front-n_basic2020overshoulderwavy": "Over Shoulder Wavy Long",
    "hair_front-n_basic2020overshoulderstraightshort": "Over Shoulder Straight Short",
    "hair_front-n_basic2020overshoulderstraightbangs": "Over Shoulder Straight Bangs",
    "hair_front-n_basic2020overshoulderstraight": "Over Shoulder Straight Long",
    "hair_front-n_basic2020overshoulderpony": "Over Shoulder Pony",
    "hair_front-n_basic2020overshouldercurly": "Over Shoulder Curly",
    "hair_front-n_basic2020overshouldercoily": "Over Shoulder Coily",
    "hair_front-n_basic2020overshoulderbraid": "Over Shoulder Braid",
    "hair_front-n_basic2019wavyoffsetpart": "Wavy Offset Part",
    "hair_front-n_basic2019wavyflipdroop": "Wavy Flipped Droopy Bang",
    "hair_front-n_basic2019wavyflipbangs": "Wavy Flipped Bangs",
    "hair_front-n_basic2019wavychunkysidebang": "Chunky Wave Side Bang",
    "hair_front-n_basic2019faceframewaves": "Face Frame Waves",
    "hair_front-n_basic2019bluntbangswithwaves": "Blunt Bangs With Loose Waves",
    "hair_front-n_basic2018wavysidebangs": "Wavy Side Bangs",
    "hair_front-n_basic2018wavypulledback": "Wavy Pulled Back",
    "hair_front-n_basic2018wavynobangs": "Wavy No Bangs",
    "hair_front-n_basic2018wavylowpart": "Wavy Low Pulled Back",
    "hair_front-n_basic2018wavyhalfup": "Wavy Half Pulled Back",
    "hair_front-n_basic2018wavyfullbangs": "Wavy Full Bangs",
    "hair_front-n_basic2018wavybettiebangs": "Bettie Bangs",
    "hair_front-n_basic2018wavybabybangs": "Wavy Baby Bangs",
    "hair_front-n_basic2018topknotwithbangs": "Top Knot with Bangs",
    "hair_front-n_basic2018topknot": "Top Knot",
    "hair_front-n_basic2018straightwhispybangs": "Straight Wispy Bangs",
    "hair_front-n_basic2018straightsidebangs": "Straight Side Bangs",
    "hair_front-n_basic2018straightpulledback": "Straight Pulled Back",
    "hair_front-n_basic2018straightnobangs": "Straight No Bangs",
    "hair_front-n_basic2018straightlowsidepart": "Straight Low Pulled Back",
    "hair_front-n_basic2018straightfullbangs": "Straight Full Bangs",
    "hair_front-n_basic2018straightbluntbangs": "Blunt Bangs",
    "hair_front-n_basic2018straightbangslowpart": "Straight Low Pulled Back With Bangs",
    "hair_front-n_basic2018straightbabybangs": "Straight Baby Bangs",
    "hair_front-n_basic2018sleekstraightpart": "Sleek Straight Part",
    "hair_front-n_basic2018sidebangspulledback": "Side Bangs Pulled Back",
    "hair_front-n_basic2018pulledbackbangs": "Pulled Back with Bangs",
    "hair_front-n_basic2018pulledback": "Simple Pulled Back",
    "hair_front-n_basic2018pigtailpart": "Pig Tail Part",
    "hair_front-n_basic2018mediumwavybettiebangs": "Bettie Bangs",
    "hair_front-n_basic2018mediumcurlymarilyn": "Marilyn Curls",
    "hair_front-n_basic2018marilyncurls": "Marilyn Curls",
    "hair_front-n_basic2018longwavytopknot": "Wavy Pulled Back Bangs",
    "hair_front-n_basic2018longstraighthalfpony": "Chunky Side Swept Bangs",
    "hair_front-n_basic2018dreadssidebangs": "Dreads Side Bangs",
    "hair_front-n_basic2018dreadspulledback": "Dreads Pulled Back",
    "hair_front-n_basic2018dreadsnobangs": "Dreads No Bangs",
    "hair_front-n_basic2018dreadsfullbangs": "Dreads Full Bangs",
    "hair_front-n_basic2018doubletopknots": "Double Top Knots",
    "hair_front-n_basic2018curlysidebangs": "Curly Side Bangs",
    "hair_front-n_basic2018curlypulledback": "Curly Pulled Back",
    "hair_front-n_basic2018curlynobangs": "Curly No Bangs",
    "hair_front-n_basic2018curlyfullbangs": "Curly Full Bangs",
    "hair_front-n_basic2018coilysidepart": "Coily Side Part",
    "hair_front-n_basic2018coilypinapple": "Coily Pinapple Hair",
    "hair_front-n_basic2018coilyhalfbun": "Coily Half Bun",
    "hair_front-n_basic2018coilssidebangs": "Coils Side Part",
    "hair_front-n_basic2018coilsfront": "Coils Front",
    "hair_front-n_basic2018buzzcut": "Bald",
    "hair_front-n_basic2018afropompoms": "Afro Pom Poms",
    "hair_front-n_basic2018afrofront": "Afro Front"
}
  },
  "hair_back": {
    "hair_back-n_malenew33": "Short Short Fro",
    "hair_back-n_malenew32": "Box Braids",
    ...
  },
  "top": {
    ...
  },
  "bottom": {
    ...
  }
}
